/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf
 */
public class AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOfTest {
    private final AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf model = new AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf();

    /**
     * Model tests for AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf
     */
    @Test
    public void testAboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf() {
        // TODO: test AboriginalIndigenousDetails37580627f49d1000257d05e999ea0000AllOf
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
