/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000
 */
public class ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000Test {
    private final ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000 model = new ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000();

    /**
     * Model tests for ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000
     */
    @Test
    public void testActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000() {
        // TODO: test ActiveMilitaryUniformedService9503dc49ae9610001fa8f76ed67d0000
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
