/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CountryA58f621b14ee1000146a3350196300e7;
import com.konfigthis.client.model.CountryCityA58f621b14ee1000146a333da1c900e6;
import com.konfigthis.client.model.CountryRegionA58f621b14ee100014b01c1cbabe00f4;
import com.konfigthis.client.model.UsageA58f621b14ee100014b01c034eeb00f3;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf
 */
public class AddressReference9c3ab7b846e4100009e5ec55fa530024AllOfTest {
    private final AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf model = new AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf();

    /**
     * Model tests for AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf
     */
    @Test
    public void testAddressReference9c3ab7b846e4100009e5ec55fa530024AllOf() {
        // TODO: test AddressReference9c3ab7b846e4100009e5ec55fa530024AllOf
    }

    /**
     * Test the property 'addressLine4Local'
     */
    @Test
    public void addressLine4LocalTest() {
        // TODO: test addressLine4Local
    }

    /**
     * Test the property 'citySubdivision2Local'
     */
    @Test
    public void citySubdivision2LocalTest() {
        // TODO: test citySubdivision2Local
    }

    /**
     * Test the property 'addressLine8Local'
     */
    @Test
    public void addressLine8LocalTest() {
        // TODO: test addressLine8Local
    }

    /**
     * Test the property 'citySubdivision1Local'
     */
    @Test
    public void citySubdivision1LocalTest() {
        // TODO: test citySubdivision1Local
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine9'
     */
    @Test
    public void addressLine9Test() {
        // TODO: test addressLine9
    }

    /**
     * Test the property 'regionSubdivision1Local'
     */
    @Test
    public void regionSubdivision1LocalTest() {
        // TODO: test regionSubdivision1Local
    }

    /**
     * Test the property 'addressLine8'
     */
    @Test
    public void addressLine8Test() {
        // TODO: test addressLine8
    }

    /**
     * Test the property 'fullFormattedAddress'
     */
    @Test
    public void fullFormattedAddressTest() {
        // TODO: test fullFormattedAddress
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'addressLine6Local'
     */
    @Test
    public void addressLine6LocalTest() {
        // TODO: test addressLine6Local
    }

    /**
     * Test the property 'regionSubdivision2'
     */
    @Test
    public void regionSubdivision2Test() {
        // TODO: test regionSubdivision2
    }

    /**
     * Test the property 'countryCity'
     */
    @Test
    public void countryCityTest() {
        // TODO: test countryCity
    }

    /**
     * Test the property 'addressLine4'
     */
    @Test
    public void addressLine4Test() {
        // TODO: test addressLine4
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'fullFormattedLocalAddress'
     */
    @Test
    public void fullFormattedLocalAddressTest() {
        // TODO: test fullFormattedLocalAddress
    }

    /**
     * Test the property 'addressLine1Local'
     */
    @Test
    public void addressLine1LocalTest() {
        // TODO: test addressLine1Local
    }

    /**
     * Test the property 'citySubdivision1'
     */
    @Test
    public void citySubdivision1Test() {
        // TODO: test citySubdivision1
    }

    /**
     * Test the property 'addressLine6'
     */
    @Test
    public void addressLine6Test() {
        // TODO: test addressLine6
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'addressLine3'
     */
    @Test
    public void addressLine3Test() {
        // TODO: test addressLine3
    }

    /**
     * Test the property 'citySubdivision2'
     */
    @Test
    public void citySubdivision2Test() {
        // TODO: test citySubdivision2
    }

    /**
     * Test the property 'addressLine9Local'
     */
    @Test
    public void addressLine9LocalTest() {
        // TODO: test addressLine9Local
    }

    /**
     * Test the property 'effective'
     */
    @Test
    public void effectiveTest() {
        // TODO: test effective
    }

    /**
     * Test the property 'addressLine7Local'
     */
    @Test
    public void addressLine7LocalTest() {
        // TODO: test addressLine7Local
    }

    /**
     * Test the property 'addressLine5'
     */
    @Test
    public void addressLine5Test() {
        // TODO: test addressLine5
    }

    /**
     * Test the property 'regionSubdivision1'
     */
    @Test
    public void regionSubdivision1Test() {
        // TODO: test regionSubdivision1
    }

    /**
     * Test the property 'cityLocal'
     */
    @Test
    public void cityLocalTest() {
        // TODO: test cityLocal
    }

    /**
     * Test the property 'addressLine2Local'
     */
    @Test
    public void addressLine2LocalTest() {
        // TODO: test addressLine2Local
    }

    /**
     * Test the property 'countryRegion'
     */
    @Test
    public void countryRegionTest() {
        // TODO: test countryRegion
    }

    /**
     * Test the property 'addressLine3Local'
     */
    @Test
    public void addressLine3LocalTest() {
        // TODO: test addressLine3Local
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'addressLine5Local'
     */
    @Test
    public void addressLine5LocalTest() {
        // TODO: test addressLine5Local
    }

    /**
     * Test the property 'addressLine7'
     */
    @Test
    public void addressLine7Test() {
        // TODO: test addressLine7
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
