/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryCityC1bb9f46f65210002d2fa2bb24a300a1
 */
public class CountryCityC1bb9f46f65210002d2fa2bb24a300a1Test {
    private final CountryCityC1bb9f46f65210002d2fa2bb24a300a1 model = new CountryCityC1bb9f46f65210002d2fa2bb24a300a1();

    /**
     * Model tests for CountryCityC1bb9f46f65210002d2fa2bb24a300a1
     */
    @Test
    public void testCountryCityC1bb9f46f65210002d2fa2bb24a300a1() {
        // TODO: test CountryCityC1bb9f46f65210002d2fa2bb24a300a1
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
