/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryA58f621b14ee1000146a3350196300e7
 */
public class CountryA58f621b14ee1000146a3350196300e7Test {
    private final CountryA58f621b14ee1000146a3350196300e7 model = new CountryA58f621b14ee1000146a3350196300e7();

    /**
     * Model tests for CountryA58f621b14ee1000146a3350196300e7
     */
    @Test
    public void testCountryA58f621b14ee1000146a3350196300e7() {
        // TODO: test CountryA58f621b14ee1000146a3350196300e7
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
