/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryC1bb9f46f65210002d2fa329fe6700b4
 */
public class CountryC1bb9f46f65210002d2fa329fe6700b4Test {
    private final CountryC1bb9f46f65210002d2fa329fe6700b4 model = new CountryC1bb9f46f65210002d2fa329fe6700b4();

    /**
     * Model tests for CountryC1bb9f46f65210002d2fa329fe6700b4
     */
    @Test
    public void testCountryC1bb9f46f65210002d2fa329fe6700b4() {
        // TODO: test CountryC1bb9f46f65210002d2fa329fe6700b4
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
