/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Country1089da0ab90910000f6e4df524710885
 */
public class Country1089da0ab90910000f6e4df524710885Test {
    private final Country1089da0ab90910000f6e4df524710885 model = new Country1089da0ab90910000f6e4df524710885();

    /**
     * Model tests for Country1089da0ab90910000f6e4df524710885
     */
    @Test
    public void testCountry1089da0ab90910000f6e4df524710885() {
        // TODO: test Country1089da0ab90910000f6e4df524710885
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
