/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Country1089da0ab90910000f6e4df524710885;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
 */
public class CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOfTest {
    private final CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf model = new CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf();

    /**
     * Model tests for CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
     */
    @Test
    public void testCountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf() {
        // TODO: test CountryPhoneCode1089da0ab90910000f6e4de36f670883AllOf
    }

    /**
     * Test the property 'countryPhoneCode'
     */
    @Test
    public void countryPhoneCodeTest() {
        // TODO: test countryPhoneCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
