/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CountryRegionA58f621b14ee100014b01c1cbabe00f4
 */
public class CountryRegionA58f621b14ee100014b01c1cbabe00f4Test {
    private final CountryRegionA58f621b14ee100014b01c1cbabe00f4 model = new CountryRegionA58f621b14ee100014b01c1cbabe00f4();

    /**
     * Model tests for CountryRegionA58f621b14ee100014b01c1cbabe00f4
     */
    @Test
    public void testCountryRegionA58f621b14ee100014b01c1cbabe00f4() {
        // TODO: test CountryRegionA58f621b14ee100014b01c1cbabe00f4
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
