/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Country80df32d43a5810000f9d096f27060127
 */
public class Country80df32d43a5810000f9d096f27060127Test {
    private final Country80df32d43a5810000f9d096f27060127 model = new Country80df32d43a5810000f9d096f27060127();

    /**
     * Model tests for Country80df32d43a5810000f9d096f27060127
     */
    @Test
    public void testCountry80df32d43a5810000f9d096f27060127() {
        // TODO: test Country80df32d43a5810000f9d096f27060127
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
