/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Usage6333dee5ac2010000c8653405aaa0038;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
 */
public class EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOfTest {
    private final EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf model = new EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf();

    /**
     * Model tests for EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
     */
    @Test
    public void testEmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf() {
        // TODO: test EmailAddressReference0918d433e86b100018119edc1b8f00f7AllOf
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
