/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Ethnicity6de928ab1284100058892e53dac501d1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf
 */
public class EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOfTest {
    private final EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf model = new EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf();

    /**
     * Model tests for EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf
     */
    @Test
    public void testEthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf() {
        // TODO: test EthnicitiesForVisualSurveyEbff7995b021100014bbd5c6cff700aeAllOf
    }

    /**
     * Test the property 'hispanicOrLatinoForVisualSurvey'
     */
    @Test
    public void hispanicOrLatinoForVisualSurveyTest() {
        // TODO: test hispanicOrLatinoForVisualSurvey
    }

    /**
     * Test the property 'ethnicities'
     */
    @Test
    public void ethnicitiesTest() {
        // TODO: test ethnicities
    }

}
