/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InstantMessengerReferenceDe08a6c876a810000cb2e38a1d2a0016;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for HomeContactInformationChangesGetStagedInstantMessengersResponse
 */
public class HomeContactInformationChangesGetStagedInstantMessengersResponseTest {
    private final HomeContactInformationChangesGetStagedInstantMessengersResponse model = new HomeContactInformationChangesGetStagedInstantMessengersResponse();

    /**
     * Model tests for HomeContactInformationChangesGetStagedInstantMessengersResponse
     */
    @Test
    public void testHomeContactInformationChangesGetStagedInstantMessengersResponse() {
        // TODO: test HomeContactInformationChangesGetStagedInstantMessengersResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
