/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Location6de928ab1284100059cd755321a501f1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MaritalStatus6de928ab1284100059b4fc2c983801e9
 */
public class MaritalStatus6de928ab1284100059b4fc2c983801e9Test {
    private final MaritalStatus6de928ab1284100059b4fc2c983801e9 model = new MaritalStatus6de928ab1284100059b4fc2c983801e9();

    /**
     * Model tests for MaritalStatus6de928ab1284100059b4fc2c983801e9
     */
    @Test
    public void testMaritalStatus6de928ab1284100059b4fc2c983801e9() {
        // TODO: test MaritalStatus6de928ab1284100059b4fc2c983801e9
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
