/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
 */
public class MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOfTest {
    private final MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf model = new MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf();

    /**
     * Model tests for MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
     */
    @Test
    public void testMediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf() {
        // TODO: test MediaDownload5d5f0fb1184b10000b16f0e5c20f0000AllOf
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'personId'
     */
    @Test
    public void personIdTest() {
        // TODO: test personId
    }

    /**
     * Test the property 'mediaId'
     */
    @Test
    public void mediaIdTest() {
        // TODO: test mediaId
    }

    /**
     * Test the property 'downloadAudio'
     */
    @Test
    public void downloadAudioTest() {
        // TODO: test downloadAudio
    }

}
