/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MedicalExam2b5dded3d48e100016120452b8710164AllOf
 */
public class MedicalExam2b5dded3d48e100016120452b8710164AllOfTest {
    private final MedicalExam2b5dded3d48e100016120452b8710164AllOf model = new MedicalExam2b5dded3d48e100016120452b8710164AllOf();

    /**
     * Model tests for MedicalExam2b5dded3d48e100016120452b8710164AllOf
     */
    @Test
    public void testMedicalExam2b5dded3d48e100016120452b8710164AllOf() {
        // TODO: test MedicalExam2b5dded3d48e100016120452b8710164AllOf
    }

    /**
     * Test the property 'lastExamDate'
     */
    @Test
    public void lastExamDateTest() {
        // TODO: test lastExamDate
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

}
