/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContentType6b9baf67ce60100011fd138066140090;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf
 */
public class PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOfTest {
    private final PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf model = new PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf();

    /**
     * Model tests for PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf
     */
    @Test
    public void testPersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf() {
        // TODO: test PersonPhoto6b9baf67ce60100007d43c79e7a30011AllOf
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'fileLength'
     */
    @Test
    public void fileLengthTest() {
        // TODO: test fileLength
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

    /**
     * Test the property 'href'
     */
    @Test
    public void hrefTest() {
        // TODO: test href
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
