/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CountryPhoneCode1089da0ab90910000f7089365467088c;
import com.konfigthis.client.model.DeviceType1089da0ab90910000f7089256c7b0888;
import com.konfigthis.client.model.Usage1089da0ab90910000f70892f2de3088a;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PhoneReference1089da0ab90910000f70891a998b0887AllOf
 */
public class PhoneReference1089da0ab90910000f70891a998b0887AllOfTest {
    private final PhoneReference1089da0ab90910000f70891a998b0887AllOf model = new PhoneReference1089da0ab90910000f70891a998b0887AllOf();

    /**
     * Model tests for PhoneReference1089da0ab90910000f70891a998b0887AllOf
     */
    @Test
    public void testPhoneReference1089da0ab90910000f70891a998b0887AllOf() {
        // TODO: test PhoneReference1089da0ab90910000f70891a998b0887AllOf
    }

    /**
     * Test the property 'extension'
     */
    @Test
    public void extensionTest() {
        // TODO: test extension
    }

    /**
     * Test the property 'completePhoneNumber'
     */
    @Test
    public void completePhoneNumberTest() {
        // TODO: test completePhoneNumber
    }

    /**
     * Test the property 'countryPhoneCode'
     */
    @Test
    public void countryPhoneCodeTest() {
        // TODO: test countryPhoneCode
    }

    /**
     * Test the property 'deviceType'
     */
    @Test
    public void deviceTypeTest() {
        // TODO: test deviceType
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
