/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Country6de928ab12841000549fe6404b2101c3;
import com.konfigthis.client.model.Region6de928ab12841000549fe6375a9301c2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5
 */
public class PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5Test {
    private final PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5 model = new PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5();

    /**
     * Model tests for PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5
     */
    @Test
    public void testPlaceOfBirth6de928ab1284100054a0b7e99c2b01c5() {
        // TODO: test PlaceOfBirth6de928ab1284100054a0b7e99c2b01c5
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

}
