/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Rank6de928ab128410005b41e4ba56a6021f
 */
public class Rank6de928ab128410005b41e4ba56a6021fTest {
    private final Rank6de928ab128410005b41e4ba56a6021f model = new Rank6de928ab128410005b41e4ba56a6021f();

    /**
     * Model tests for Rank6de928ab128410005b41e4ba56a6021f
     */
    @Test
    public void testRank6de928ab128410005b41e4ba56a6021f() {
        // TODO: test Rank6de928ab128410005b41e4ba56a6021f
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
