/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AcademicSuffixE08d883b5eae10000403d7c0735402e9;
import com.konfigthis.client.model.CountryE08d883b5eae10000403d7c8e60502eb;
import com.konfigthis.client.model.HereditarySuffixE08d883b5eae10000403d7efe24b02f3;
import com.konfigthis.client.model.HonorarySuffixE08d883b5eae10000403d7acba9602e5;
import com.konfigthis.client.model.LocalPersonNameE08d883b5eae10000403d7cd713c02ec;
import com.konfigthis.client.model.ProfessionalSuffixE08d883b5eae10000403d7e2171f02f0;
import com.konfigthis.client.model.RelativeTypeE08d883b5eae1000040cc1231a5902f5;
import com.konfigthis.client.model.ReligiousSuffixE08d883b5eae10000403d7eb401e02f2;
import com.konfigthis.client.model.RoyalSuffixE08d883b5eae10000403d7d259db02ed;
import com.konfigthis.client.model.SalutationSuffixE08d883b5eae10000403d7d736c102ee;
import com.konfigthis.client.model.SocialSuffixE08d883b5eae10000403d7dc081502ef;
import com.konfigthis.client.model.TitleE08d883b5eae10000403d7b62abb02e7;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RelativeNamesE08d883b5eae10000403d79fe6d202e3
 */
public class RelativeNamesE08d883b5eae10000403d79fe6d202e3Test {
    private final RelativeNamesE08d883b5eae10000403d79fe6d202e3 model = new RelativeNamesE08d883b5eae10000403d79fe6d202e3();

    /**
     * Model tests for RelativeNamesE08d883b5eae10000403d79fe6d202e3
     */
    @Test
    public void testRelativeNamesE08d883b5eae10000403d79fe6d202e3() {
        // TODO: test RelativeNamesE08d883b5eae10000403d79fe6d202e3
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'royalSuffix'
     */
    @Test
    public void royalSuffixTest() {
        // TODO: test royalSuffix
    }

    /**
     * Test the property 'religiousSuffix'
     */
    @Test
    public void religiousSuffixTest() {
        // TODO: test religiousSuffix
    }

    /**
     * Test the property 'localPersonName'
     */
    @Test
    public void localPersonNameTest() {
        // TODO: test localPersonName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'honorarySuffix'
     */
    @Test
    public void honorarySuffixTest() {
        // TODO: test honorarySuffix
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'secondaryLastName'
     */
    @Test
    public void secondaryLastNameTest() {
        // TODO: test secondaryLastName
    }

    /**
     * Test the property 'salutationSuffix'
     */
    @Test
    public void salutationSuffixTest() {
        // TODO: test salutationSuffix
    }

    /**
     * Test the property 'relativeType'
     */
    @Test
    public void relativeTypeTest() {
        // TODO: test relativeType
    }

    /**
     * Test the property 'socialSuffix'
     */
    @Test
    public void socialSuffixTest() {
        // TODO: test socialSuffix
    }

    /**
     * Test the property 'professionalSuffix'
     */
    @Test
    public void professionalSuffixTest() {
        // TODO: test professionalSuffix
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'academicSuffix'
     */
    @Test
    public void academicSuffixTest() {
        // TODO: test academicSuffix
    }

    /**
     * Test the property 'hereditarySuffix'
     */
    @Test
    public void hereditarySuffixTest() {
        // TODO: test hereditarySuffix
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
