/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Salutation11c67b72c9c610000edf7291ae7b004c
 */
public class Salutation11c67b72c9c610000edf7291ae7b004cTest {
    private final Salutation11c67b72c9c610000edf7291ae7b004c model = new Salutation11c67b72c9c610000edf7291ae7b004c();

    /**
     * Model tests for Salutation11c67b72c9c610000edf7291ae7b004c
     */
    @Test
    public void testSalutation11c67b72c9c610000edf7291ae7b004c() {
        // TODO: test Salutation11c67b72c9c610000edf7291ae7b004c
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
