/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SocialSuffixE08d883b5eae10000403d7dc081502ef
 */
public class SocialSuffixE08d883b5eae10000403d7dc081502efTest {
    private final SocialSuffixE08d883b5eae10000403d7dc081502ef model = new SocialSuffixE08d883b5eae10000403d7dc081502ef();

    /**
     * Model tests for SocialSuffixE08d883b5eae10000403d7dc081502ef
     */
    @Test
    public void testSocialSuffixE08d883b5eae10000403d7dc081502ef() {
        // TODO: test SocialSuffixE08d883b5eae10000403d7dc081502ef
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
