/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UniformServiceReserveStatus9503dc49ae9610001e48857455610000
 */
public class UniformServiceReserveStatus9503dc49ae9610001e48857455610000Test {
    private final UniformServiceReserveStatus9503dc49ae9610001e48857455610000 model = new UniformServiceReserveStatus9503dc49ae9610001e48857455610000();

    /**
     * Model tests for UniformServiceReserveStatus9503dc49ae9610001e48857455610000
     */
    @Test
    public void testUniformServiceReserveStatus9503dc49ae9610001e48857455610000() {
        // TODO: test UniformServiceReserveStatus9503dc49ae9610001e48857455610000
    }

    /**
     * Test the property 'uniformServiceReserveStatusDescription'
     */
    @Test
    public void uniformServiceReserveStatusDescriptionTest() {
        // TODO: test uniformServiceReserveStatusDescription
    }

    /**
     * Test the property 'uniformServiceReserveStatusName'
     */
    @Test
    public void uniformServiceReserveStatusNameTest() {
        // TODO: test uniformServiceReserveStatusName
    }

    /**
     * Test the property 'uniformServiceReserveStatusCode'
     */
    @Test
    public void uniformServiceReserveStatusCodeTest() {
        // TODO: test uniformServiceReserveStatusCode
    }

    /**
     * Test the property 'inactive'
     */
    @Test
    public void inactiveTest() {
        // TODO: test inactive
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
