/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UniversalIDE451ce2c8b48100007c31392a1ff00c2
 */
public class UniversalIDE451ce2c8b48100007c31392a1ff00c2Test {
    private final UniversalIDE451ce2c8b48100007c31392a1ff00c2 model = new UniversalIDE451ce2c8b48100007c31392a1ff00c2();

    /**
     * Model tests for UniversalIDE451ce2c8b48100007c31392a1ff00c2
     */
    @Test
    public void testUniversalIDE451ce2c8b48100007c31392a1ff00c2() {
        // TODO: test UniversalIDE451ce2c8b48100007c31392a1ff00c2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
