/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsageType901718dd5e7910000cc03935c73e029cAllOf
 */
public class UsageType901718dd5e7910000cc03935c73e029cAllOfTest {
    private final UsageType901718dd5e7910000cc03935c73e029cAllOf model = new UsageType901718dd5e7910000cc03935c73e029cAllOf();

    /**
     * Model tests for UsageType901718dd5e7910000cc03935c73e029cAllOf
     */
    @Test
    public void testUsageType901718dd5e7910000cc03935c73e029cAllOf() {
        // TODO: test UsageType901718dd5e7910000cc03935c73e029cAllOf
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
