/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsageType51665e7371e310000f554a00d31000f2
 */
public class UsageType51665e7371e310000f554a00d31000f2Test {
    private final UsageType51665e7371e310000f554a00d31000f2 model = new UsageType51665e7371e310000f554a00d31000f2();

    /**
     * Model tests for UsageType51665e7371e310000f554a00d31000f2
     */
    @Test
    public void testUsageType51665e7371e310000f554a00d31000f2() {
        // TODO: test UsageType51665e7371e310000f554a00d31000f2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
