/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UsageAb827579ee171000225b0b528418019f;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebAddress33e26848dc0010003893a0202ced0165AllOf
 */
public class WebAddress33e26848dc0010003893a0202ced0165AllOfTest {
    private final WebAddress33e26848dc0010003893a0202ced0165AllOf model = new WebAddress33e26848dc0010003893a0202ced0165AllOf();

    /**
     * Model tests for WebAddress33e26848dc0010003893a0202ced0165AllOf
     */
    @Test
    public void testWebAddress33e26848dc0010003893a0202ced0165AllOf() {
        // TODO: test WebAddress33e26848dc0010003893a0202ced0165AllOf
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
