/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UsageE357ae6d466510000ce25a08bfe401b3;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf
 */
public class WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOfTest {
    private final WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf model = new WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf();

    /**
     * Model tests for WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf
     */
    @Test
    public void testWebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf() {
        // TODO: test WebAddressReferenceE357ae6d466510000ce259f323be01b0AllOf
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
