/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkerDocument15d8b82e323110000e0117c92d9803b2
 */
public class WorkerDocument15d8b82e323110000e0117c92d9803b2Test {
    private final WorkerDocument15d8b82e323110000e0117c92d9803b2 model = new WorkerDocument15d8b82e323110000e0117c92d9803b2();

    /**
     * Model tests for WorkerDocument15d8b82e323110000e0117c92d9803b2
     */
    @Test
    public void testWorkerDocument15d8b82e323110000e0117c92d9803b2() {
        // TODO: test WorkerDocument15d8b82e323110000e0117c92d9803b2
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'fileName'
     */
    @Test
    public void fileNameTest() {
        // TODO: test fileName
    }

}
