/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Type33e26848dc00100037bb584480fe014a;
import com.konfigthis.client.model.UsageAb827579ee1710002266db48222201a4;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * InstantMessengerAccount33e26848dc00100036f723337ebb0132
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InstantMessengerAccount33e26848dc00100036f723337ebb0132 {
  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Type33e26848dc00100037bb584480fe014a type;

  public static final String SERIALIZED_NAME_USER_NAME = "userName";
  @SerializedName(SERIALIZED_NAME_USER_NAME)
  private String userName;

  public static final String SERIALIZED_NAME_USAGE = "usage";
  @SerializedName(SERIALIZED_NAME_USAGE)
  private UsageAb827579ee1710002266db48222201a4 usage;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public InstantMessengerAccount33e26848dc00100036f723337ebb0132() {
  }

  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 comment(String comment) {
    
    
    
    
    this.comment = comment;
    return this;
  }

   /**
   * The comment associated with the instant messenger account.
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The comment associated with the instant messenger account.")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    
    
    
    this.comment = comment;
  }


  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 type(Type33e26848dc00100037bb584480fe014a type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Type33e26848dc00100037bb584480fe014a getType() {
    return type;
  }


  public void setType(Type33e26848dc00100037bb584480fe014a type) {
    
    
    
    this.type = type;
  }


  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 userName(String userName) {
    
    
    
    
    this.userName = userName;
    return this;
  }

   /**
   * The instant messenger account username.
   * @return userName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The instant messenger account username.")

  public String getUserName() {
    return userName;
  }


  public void setUserName(String userName) {
    
    
    
    this.userName = userName;
  }


  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 usage(UsageAb827579ee1710002266db48222201a4 usage) {
    
    
    
    
    this.usage = usage;
    return this;
  }

   /**
   * Get usage
   * @return usage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UsageAb827579ee1710002266db48222201a4 getUsage() {
    return usage;
  }


  public void setUsage(UsageAb827579ee1710002266db48222201a4 usage) {
    
    
    
    this.usage = usage;
  }


  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InstantMessengerAccount33e26848dc00100036f723337ebb0132 instance itself
   */
  public InstantMessengerAccount33e26848dc00100036f723337ebb0132 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstantMessengerAccount33e26848dc00100036f723337ebb0132 instantMessengerAccount33e26848dc00100036f723337ebb0132 = (InstantMessengerAccount33e26848dc00100036f723337ebb0132) o;
    return Objects.equals(this.comment, instantMessengerAccount33e26848dc00100036f723337ebb0132.comment) &&
        Objects.equals(this.type, instantMessengerAccount33e26848dc00100036f723337ebb0132.type) &&
        Objects.equals(this.userName, instantMessengerAccount33e26848dc00100036f723337ebb0132.userName) &&
        Objects.equals(this.usage, instantMessengerAccount33e26848dc00100036f723337ebb0132.usage) &&
        Objects.equals(this.id, instantMessengerAccount33e26848dc00100036f723337ebb0132.id)&&
        Objects.equals(this.additionalProperties, instantMessengerAccount33e26848dc00100036f723337ebb0132.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, type, userName, usage, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstantMessengerAccount33e26848dc00100036f723337ebb0132 {\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment");
    openapiFields.add("type");
    openapiFields.add("userName");
    openapiFields.add("usage");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InstantMessengerAccount33e26848dc00100036f723337ebb0132
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InstantMessengerAccount33e26848dc00100036f723337ebb0132.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InstantMessengerAccount33e26848dc00100036f723337ebb0132 is not found in the empty JSON string", InstantMessengerAccount33e26848dc00100036f723337ebb0132.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        Type33e26848dc00100037bb584480fe014a.validateJsonObject(jsonObj.getAsJsonObject("type"));
      }
      if ((jsonObj.get("userName") != null && !jsonObj.get("userName").isJsonNull()) && !jsonObj.get("userName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userName").toString()));
      }
      // validate the optional field `usage`
      if (jsonObj.get("usage") != null && !jsonObj.get("usage").isJsonNull()) {
        UsageAb827579ee1710002266db48222201a4.validateJsonObject(jsonObj.getAsJsonObject("usage"));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InstantMessengerAccount33e26848dc00100036f723337ebb0132.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InstantMessengerAccount33e26848dc00100036f723337ebb0132' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InstantMessengerAccount33e26848dc00100036f723337ebb0132> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InstantMessengerAccount33e26848dc00100036f723337ebb0132.class));

       return (TypeAdapter<T>) new TypeAdapter<InstantMessengerAccount33e26848dc00100036f723337ebb0132>() {
           @Override
           public void write(JsonWriter out, InstantMessengerAccount33e26848dc00100036f723337ebb0132 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InstantMessengerAccount33e26848dc00100036f723337ebb0132 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InstantMessengerAccount33e26848dc00100036f723337ebb0132 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InstantMessengerAccount33e26848dc00100036f723337ebb0132 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InstantMessengerAccount33e26848dc00100036f723337ebb0132
  * @throws IOException if the JSON string is invalid with respect to InstantMessengerAccount33e26848dc00100036f723337ebb0132
  */
  public static InstantMessengerAccount33e26848dc00100036f723337ebb0132 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InstantMessengerAccount33e26848dc00100036f723337ebb0132.class);
  }

 /**
  * Convert an instance of InstantMessengerAccount33e26848dc00100036f723337ebb0132 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

