/*
 * person
 * The Person REST APIs enable you to access information about the worker person, including country-specific configuration information about name components.
 *
 * The version of the OpenAPI document: v4
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Country33e26848dc0010002f1ae802adc30074;
import com.konfigthis.client.model.Hereditary11c67b72c9c610000edf72cf8506004d;
import com.konfigthis.client.model.Salutation11c67b72c9c610000edf7291ae7b004c;
import com.konfigthis.client.model.Social11c67b72c9c610000edf72e003d1004e;
import com.konfigthis.client.model.Title11c67b72c9c610000edf72f0b3c5004f;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Name33e26848dc0010002f1ae76d63ec0061
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Name33e26848dc0010002f1ae76d63ec0061 {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private Title11c67b72c9c610000edf72f0b3c5004f title;

  public static final String SERIALIZED_NAME_SECONDARY_LOCAL = "secondaryLocal";
  @SerializedName(SERIALIZED_NAME_SECONDARY_LOCAL)
  private String secondaryLocal;

  public static final String SERIALIZED_NAME_SECONDARY_LAST = "secondaryLast";
  @SerializedName(SERIALIZED_NAME_SECONDARY_LAST)
  private String secondaryLast;

  public static final String SERIALIZED_NAME_SALUTATION = "salutation";
  @SerializedName(SERIALIZED_NAME_SALUTATION)
  private Salutation11c67b72c9c610000edf7291ae7b004c salutation;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private String primary;

  public static final String SERIALIZED_NAME_PRIMARY_LOCAL2 = "primaryLocal2";
  @SerializedName(SERIALIZED_NAME_PRIMARY_LOCAL2)
  private String primaryLocal2;

  public static final String SERIALIZED_NAME_TERTIARY_LAST = "tertiaryLast";
  @SerializedName(SERIALIZED_NAME_TERTIARY_LAST)
  private String tertiaryLast;

  public static final String SERIALIZED_NAME_FULL = "full";
  @SerializedName(SERIALIZED_NAME_FULL)
  private String full;

  public static final String SERIALIZED_NAME_SOCIAL = "social";
  @SerializedName(SERIALIZED_NAME_SOCIAL)
  private Social11c67b72c9c610000edf72e003d1004e social;

  public static final String SERIALIZED_NAME_FIRST_LOCAL = "firstLocal";
  @SerializedName(SERIALIZED_NAME_FIRST_LOCAL)
  private String firstLocal;

  public static final String SERIALIZED_NAME_FIRST = "first";
  @SerializedName(SERIALIZED_NAME_FIRST)
  private String first;

  public static final String SERIALIZED_NAME_HEREDITARY = "hereditary";
  @SerializedName(SERIALIZED_NAME_HEREDITARY)
  private Hereditary11c67b72c9c610000edf72cf8506004d hereditary;

  public static final String SERIALIZED_NAME_MIDDLE_LOCAL = "middleLocal";
  @SerializedName(SERIALIZED_NAME_MIDDLE_LOCAL)
  private String middleLocal;

  public static final String SERIALIZED_NAME_FIRST_LOCAL2 = "firstLocal2";
  @SerializedName(SERIALIZED_NAME_FIRST_LOCAL2)
  private String firstLocal2;

  public static final String SERIALIZED_NAME_PRIMARY_LOCAL = "primaryLocal";
  @SerializedName(SERIALIZED_NAME_PRIMARY_LOCAL)
  private String primaryLocal;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private Country33e26848dc0010002f1ae802adc30074 country;

  public static final String SERIALIZED_NAME_MIDDLE = "middle";
  @SerializedName(SERIALIZED_NAME_MIDDLE)
  private String middle;

  public static final String SERIALIZED_NAME_DESCRIPTOR = "descriptor";
  @SerializedName(SERIALIZED_NAME_DESCRIPTOR)
  private String descriptor;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public Name33e26848dc0010002f1ae76d63ec0061() {
  }

  public Name33e26848dc0010002f1ae76d63ec0061 title(Title11c67b72c9c610000edf72f0b3c5004f title) {
    
    
    
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Title11c67b72c9c610000edf72f0b3c5004f getTitle() {
    return title;
  }


  public void setTitle(Title11c67b72c9c610000edf72f0b3c5004f title) {
    
    
    
    this.title = title;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 secondaryLocal(String secondaryLocal) {
    
    
    
    
    this.secondaryLocal = secondaryLocal;
    return this;
  }

   /**
   * The person&#39;s secondary family name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return secondaryLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's secondary family name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getSecondaryLocal() {
    return secondaryLocal;
  }


  public void setSecondaryLocal(String secondaryLocal) {
    
    
    
    this.secondaryLocal = secondaryLocal;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 secondaryLast(String secondaryLast) {
    
    
    
    
    this.secondaryLast = secondaryLast;
    return this;
  }

   /**
   * The secondary family name for a person.
   * @return secondaryLast
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The secondary family name for a person.")

  public String getSecondaryLast() {
    return secondaryLast;
  }


  public void setSecondaryLast(String secondaryLast) {
    
    
    
    this.secondaryLast = secondaryLast;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 salutation(Salutation11c67b72c9c610000edf7291ae7b004c salutation) {
    
    
    
    
    this.salutation = salutation;
    return this;
  }

   /**
   * Get salutation
   * @return salutation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Salutation11c67b72c9c610000edf7291ae7b004c getSalutation() {
    return salutation;
  }


  public void setSalutation(Salutation11c67b72c9c610000edf7291ae7b004c salutation) {
    
    
    
    this.salutation = salutation;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 primary(String primary) {
    
    
    
    
    this.primary = primary;
    return this;
  }

   /**
   * The person&#39;s family name.
   * @return primary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's family name.")

  public String getPrimary() {
    return primary;
  }


  public void setPrimary(String primary) {
    
    
    
    this.primary = primary;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 primaryLocal2(String primaryLocal2) {
    
    
    
    
    this.primaryLocal2 = primaryLocal2;
    return this;
  }

   /**
   * The person&#39;s last name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return primaryLocal2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's last name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getPrimaryLocal2() {
    return primaryLocal2;
  }


  public void setPrimaryLocal2(String primaryLocal2) {
    
    
    
    this.primaryLocal2 = primaryLocal2;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 tertiaryLast(String tertiaryLast) {
    
    
    
    
    this.tertiaryLast = tertiaryLast;
    return this;
  }

   /**
   * The person&#39;s tertiary last name.
   * @return tertiaryLast
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's tertiary last name.")

  public String getTertiaryLast() {
    return tertiaryLast;
  }


  public void setTertiaryLast(String tertiaryLast) {
    
    
    
    this.tertiaryLast = tertiaryLast;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 full(String full) {
    
    
    
    
    this.full = full;
    return this;
  }

   /**
   * The Full Name for a person, when it is provided. Workday only tracks Full Name for countries where the Full Name name component is used.
   * @return full
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The Full Name for a person, when it is provided. Workday only tracks Full Name for countries where the Full Name name component is used.")

  public String getFull() {
    return full;
  }


  public void setFull(String full) {
    
    
    
    this.full = full;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 social(Social11c67b72c9c610000edf72e003d1004e social) {
    
    
    
    
    this.social = social;
    return this;
  }

   /**
   * Get social
   * @return social
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Social11c67b72c9c610000edf72e003d1004e getSocial() {
    return social;
  }


  public void setSocial(Social11c67b72c9c610000edf72e003d1004e social) {
    
    
    
    this.social = social;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 firstLocal(String firstLocal) {
    
    
    
    
    this.firstLocal = firstLocal;
    return this;
  }

   /**
   * The person&#39;s given name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return firstLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's given name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getFirstLocal() {
    return firstLocal;
  }


  public void setFirstLocal(String firstLocal) {
    
    
    
    this.firstLocal = firstLocal;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 first(String first) {
    
    
    
    
    this.first = first;
    return this;
  }

   /**
   * The first or given name for a person.
   * @return first
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The first or given name for a person.")

  public String getFirst() {
    return first;
  }


  public void setFirst(String first) {
    
    
    
    this.first = first;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 hereditary(Hereditary11c67b72c9c610000edf72cf8506004d hereditary) {
    
    
    
    
    this.hereditary = hereditary;
    return this;
  }

   /**
   * Get hereditary
   * @return hereditary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Hereditary11c67b72c9c610000edf72cf8506004d getHereditary() {
    return hereditary;
  }


  public void setHereditary(Hereditary11c67b72c9c610000edf72cf8506004d hereditary) {
    
    
    
    this.hereditary = hereditary;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 middleLocal(String middleLocal) {
    
    
    
    
    this.middleLocal = middleLocal;
    return this;
  }

   /**
   * The person&#39;s middle name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return middleLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's middle name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getMiddleLocal() {
    return middleLocal;
  }


  public void setMiddleLocal(String middleLocal) {
    
    
    
    this.middleLocal = middleLocal;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 firstLocal2(String firstLocal2) {
    
    
    
    
    this.firstLocal2 = firstLocal2;
    return this;
  }

   /**
   * The person&#39;s given name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return firstLocal2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's given name in second local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getFirstLocal2() {
    return firstLocal2;
  }


  public void setFirstLocal2(String firstLocal2) {
    
    
    
    this.firstLocal2 = firstLocal2;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 primaryLocal(String primaryLocal) {
    
    
    
    
    this.primaryLocal = primaryLocal;
    return this;
  }

   /**
   * The person&#39;s last name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.
   * @return primaryLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The person's last name in local script.  Workday only tracks local names for countries where a non-Latin script is commonly used.")

  public String getPrimaryLocal() {
    return primaryLocal;
  }


  public void setPrimaryLocal(String primaryLocal) {
    
    
    
    this.primaryLocal = primaryLocal;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 country(Country33e26848dc0010002f1ae802adc30074 country) {
    
    
    
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Country33e26848dc0010002f1ae802adc30074 getCountry() {
    return country;
  }


  public void setCountry(Country33e26848dc0010002f1ae802adc30074 country) {
    
    
    
    this.country = country;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 middle(String middle) {
    
    
    
    
    this.middle = middle;
    return this;
  }

   /**
   * The middle name from the name.
   * @return middle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit amet, cum choro singulis consectetuer ut, ubique iisque contentiones ex duo. Quo lorem etiam eu.", value = "The middle name from the name.")

  public String getMiddle() {
    return middle;
  }


  public void setMiddle(String middle) {
    
    
    
    this.middle = middle;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 descriptor(String descriptor) {
    
    
    
    
    this.descriptor = descriptor;
    return this;
  }

   /**
   * A preview of the instance
   * @return descriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Lorem ipsum dolor sit ame", value = "A preview of the instance")

  public String getDescriptor() {
    return descriptor;
  }


  public void setDescriptor(String descriptor) {
    
    
    
    this.descriptor = descriptor;
  }


  public Name33e26848dc0010002f1ae76d63ec0061 id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Id of the instance
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the instance")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Name33e26848dc0010002f1ae76d63ec0061 instance itself
   */
  public Name33e26848dc0010002f1ae76d63ec0061 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Name33e26848dc0010002f1ae76d63ec0061 name33e26848dc0010002f1ae76d63ec0061 = (Name33e26848dc0010002f1ae76d63ec0061) o;
    return Objects.equals(this.title, name33e26848dc0010002f1ae76d63ec0061.title) &&
        Objects.equals(this.secondaryLocal, name33e26848dc0010002f1ae76d63ec0061.secondaryLocal) &&
        Objects.equals(this.secondaryLast, name33e26848dc0010002f1ae76d63ec0061.secondaryLast) &&
        Objects.equals(this.salutation, name33e26848dc0010002f1ae76d63ec0061.salutation) &&
        Objects.equals(this.primary, name33e26848dc0010002f1ae76d63ec0061.primary) &&
        Objects.equals(this.primaryLocal2, name33e26848dc0010002f1ae76d63ec0061.primaryLocal2) &&
        Objects.equals(this.tertiaryLast, name33e26848dc0010002f1ae76d63ec0061.tertiaryLast) &&
        Objects.equals(this.full, name33e26848dc0010002f1ae76d63ec0061.full) &&
        Objects.equals(this.social, name33e26848dc0010002f1ae76d63ec0061.social) &&
        Objects.equals(this.firstLocal, name33e26848dc0010002f1ae76d63ec0061.firstLocal) &&
        Objects.equals(this.first, name33e26848dc0010002f1ae76d63ec0061.first) &&
        Objects.equals(this.hereditary, name33e26848dc0010002f1ae76d63ec0061.hereditary) &&
        Objects.equals(this.middleLocal, name33e26848dc0010002f1ae76d63ec0061.middleLocal) &&
        Objects.equals(this.firstLocal2, name33e26848dc0010002f1ae76d63ec0061.firstLocal2) &&
        Objects.equals(this.primaryLocal, name33e26848dc0010002f1ae76d63ec0061.primaryLocal) &&
        Objects.equals(this.country, name33e26848dc0010002f1ae76d63ec0061.country) &&
        Objects.equals(this.middle, name33e26848dc0010002f1ae76d63ec0061.middle) &&
        Objects.equals(this.descriptor, name33e26848dc0010002f1ae76d63ec0061.descriptor) &&
        Objects.equals(this.id, name33e26848dc0010002f1ae76d63ec0061.id)&&
        Objects.equals(this.additionalProperties, name33e26848dc0010002f1ae76d63ec0061.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, secondaryLocal, secondaryLast, salutation, primary, primaryLocal2, tertiaryLast, full, social, firstLocal, first, hereditary, middleLocal, firstLocal2, primaryLocal, country, middle, descriptor, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Name33e26848dc0010002f1ae76d63ec0061 {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    secondaryLocal: ").append(toIndentedString(secondaryLocal)).append("\n");
    sb.append("    secondaryLast: ").append(toIndentedString(secondaryLast)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    primaryLocal2: ").append(toIndentedString(primaryLocal2)).append("\n");
    sb.append("    tertiaryLast: ").append(toIndentedString(tertiaryLast)).append("\n");
    sb.append("    full: ").append(toIndentedString(full)).append("\n");
    sb.append("    social: ").append(toIndentedString(social)).append("\n");
    sb.append("    firstLocal: ").append(toIndentedString(firstLocal)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    hereditary: ").append(toIndentedString(hereditary)).append("\n");
    sb.append("    middleLocal: ").append(toIndentedString(middleLocal)).append("\n");
    sb.append("    firstLocal2: ").append(toIndentedString(firstLocal2)).append("\n");
    sb.append("    primaryLocal: ").append(toIndentedString(primaryLocal)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    middle: ").append(toIndentedString(middle)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("secondaryLocal");
    openapiFields.add("secondaryLast");
    openapiFields.add("salutation");
    openapiFields.add("primary");
    openapiFields.add("primaryLocal2");
    openapiFields.add("tertiaryLast");
    openapiFields.add("full");
    openapiFields.add("social");
    openapiFields.add("firstLocal");
    openapiFields.add("first");
    openapiFields.add("hereditary");
    openapiFields.add("middleLocal");
    openapiFields.add("firstLocal2");
    openapiFields.add("primaryLocal");
    openapiFields.add("country");
    openapiFields.add("middle");
    openapiFields.add("descriptor");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Name33e26848dc0010002f1ae76d63ec0061
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Name33e26848dc0010002f1ae76d63ec0061.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Name33e26848dc0010002f1ae76d63ec0061 is not found in the empty JSON string", Name33e26848dc0010002f1ae76d63ec0061.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `title`
      if (jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) {
        Title11c67b72c9c610000edf72f0b3c5004f.validateJsonObject(jsonObj.getAsJsonObject("title"));
      }
      if ((jsonObj.get("secondaryLocal") != null && !jsonObj.get("secondaryLocal").isJsonNull()) && !jsonObj.get("secondaryLocal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secondaryLocal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secondaryLocal").toString()));
      }
      if ((jsonObj.get("secondaryLast") != null && !jsonObj.get("secondaryLast").isJsonNull()) && !jsonObj.get("secondaryLast").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secondaryLast` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secondaryLast").toString()));
      }
      // validate the optional field `salutation`
      if (jsonObj.get("salutation") != null && !jsonObj.get("salutation").isJsonNull()) {
        Salutation11c67b72c9c610000edf7291ae7b004c.validateJsonObject(jsonObj.getAsJsonObject("salutation"));
      }
      if ((jsonObj.get("primary") != null && !jsonObj.get("primary").isJsonNull()) && !jsonObj.get("primary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primary").toString()));
      }
      if ((jsonObj.get("primaryLocal2") != null && !jsonObj.get("primaryLocal2").isJsonNull()) && !jsonObj.get("primaryLocal2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryLocal2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryLocal2").toString()));
      }
      if ((jsonObj.get("tertiaryLast") != null && !jsonObj.get("tertiaryLast").isJsonNull()) && !jsonObj.get("tertiaryLast").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tertiaryLast` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tertiaryLast").toString()));
      }
      if ((jsonObj.get("full") != null && !jsonObj.get("full").isJsonNull()) && !jsonObj.get("full").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `full` to be a primitive type in the JSON string but got `%s`", jsonObj.get("full").toString()));
      }
      // validate the optional field `social`
      if (jsonObj.get("social") != null && !jsonObj.get("social").isJsonNull()) {
        Social11c67b72c9c610000edf72e003d1004e.validateJsonObject(jsonObj.getAsJsonObject("social"));
      }
      if ((jsonObj.get("firstLocal") != null && !jsonObj.get("firstLocal").isJsonNull()) && !jsonObj.get("firstLocal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstLocal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstLocal").toString()));
      }
      if ((jsonObj.get("first") != null && !jsonObj.get("first").isJsonNull()) && !jsonObj.get("first").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `first` to be a primitive type in the JSON string but got `%s`", jsonObj.get("first").toString()));
      }
      // validate the optional field `hereditary`
      if (jsonObj.get("hereditary") != null && !jsonObj.get("hereditary").isJsonNull()) {
        Hereditary11c67b72c9c610000edf72cf8506004d.validateJsonObject(jsonObj.getAsJsonObject("hereditary"));
      }
      if ((jsonObj.get("middleLocal") != null && !jsonObj.get("middleLocal").isJsonNull()) && !jsonObj.get("middleLocal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `middleLocal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("middleLocal").toString()));
      }
      if ((jsonObj.get("firstLocal2") != null && !jsonObj.get("firstLocal2").isJsonNull()) && !jsonObj.get("firstLocal2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstLocal2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstLocal2").toString()));
      }
      if ((jsonObj.get("primaryLocal") != null && !jsonObj.get("primaryLocal").isJsonNull()) && !jsonObj.get("primaryLocal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryLocal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryLocal").toString()));
      }
      // validate the optional field `country`
      if (jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) {
        Country33e26848dc0010002f1ae802adc30074.validateJsonObject(jsonObj.getAsJsonObject("country"));
      }
      if ((jsonObj.get("middle") != null && !jsonObj.get("middle").isJsonNull()) && !jsonObj.get("middle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `middle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("middle").toString()));
      }
      if ((jsonObj.get("descriptor") != null && !jsonObj.get("descriptor").isJsonNull()) && !jsonObj.get("descriptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptor").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Name33e26848dc0010002f1ae76d63ec0061.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Name33e26848dc0010002f1ae76d63ec0061' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Name33e26848dc0010002f1ae76d63ec0061> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Name33e26848dc0010002f1ae76d63ec0061.class));

       return (TypeAdapter<T>) new TypeAdapter<Name33e26848dc0010002f1ae76d63ec0061>() {
           @Override
           public void write(JsonWriter out, Name33e26848dc0010002f1ae76d63ec0061 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Name33e26848dc0010002f1ae76d63ec0061 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Name33e26848dc0010002f1ae76d63ec0061 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Name33e26848dc0010002f1ae76d63ec0061 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Name33e26848dc0010002f1ae76d63ec0061
  * @throws IOException if the JSON string is invalid with respect to Name33e26848dc0010002f1ae76d63ec0061
  */
  public static Name33e26848dc0010002f1ae76d63ec0061 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Name33e26848dc0010002f1ae76d63ec0061.class);
  }

 /**
  * Convert an instance of Name33e26848dc0010002f1ae76d63ec0061 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

